### ISSUE TITLE
Examples not visible on r-nimble.org

### ISSUE THREAD

**Issue by gauravsk** [nimble-dev/nimble-demos#4]
Hi- I'm writing to report that I'm getting the following error on the examples page of r-nimble.org: 

`You don't have permission to access /~pdevalpine/nimbleExamples/build_a_model/nimble_build_a_model.html on this server.`  

I see now that the examples are all available at this repo; just wanted to give a heads up on this.

![screenshot of r-nimble](https://user-images.githubusercontent.com/6154868/29324985-eb1a158a-819a-11e7-8dd8-c22161ec9d2a.png)

**Comment by perrydv** [comment]
@gauravsk Thanks for letting us know about this issue.  I'm not able to reproduce the problem, even when I try from outside our campus network.  There was some recent maintenance downtime on the host servers.  Would you mind trying again and confirming if it still doesn't work?  Thanks!

**Comment by gauravsk** [comment]
Oh, this is weird. I can see the examples from Chrome; I only get the error when I try to access from Firefox (running Firefox 54.0 on Ubuntu 16.1). Actually, I get a new error message now: 


![screenshot from 2017-08-15 14-55-33](https://user-images.githubusercontent.com/6154868/29338453-2d6daa94-81ca-11e7-9baa-d525bec7b95f.png)

Thanks for your work on this project, excited to explore and hopefully use it over the next few months!

**Comment by gauravsk** [comment]
works now on firefox as well!

**Comment by perrydv** [comment]
Phew, thanks!
